### ISSUE TITLE
CORRIGIR: Código em uma linha

### ISSUE THREAD

**Issue by rafaelcorsi** [EduardoMVAz/bits-e-proc-GrupoEmbasbacado#42]
Corrigir essa lógica que foi feita toda em uma única linha, isso foi proposital? ou de problema de quebra de linha?

https://github.com/EduardoMVAz/bits-e-proc-GrupoEmbasbacado/blob/5366393be3a601b39ea25ff5cdcaa620196a2a02/hw/components.py#L160

https://github.com/EduardoMVAz/bits-e-proc-GrupoEmbasbacado/blob/5366393be3a601b39ea25ff5cdcaa620196a2a02/hw/components.py#L177

Tem mais no arquivo...

**Comment by PedroPertusi** [comment]
Erro corrigido.
